export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Rules } from './Rules'
export { default as NotFound } from './NotFound'
export { default as Product } from './Product/Product'
export { default as Cart } from './Cart/Cart'
